### PR TITLE
change favicon to small green logo

### PR DESCRIPTION
**Pull request by priyald17**
Attempting to change favicon but it looks a little stretched. Compare to e.g. the CCAI wiki. Any way we can make it a bit less stretched (@asross)?
image

This is the Wiki favicon link for reference (SVG version of our logo): https://static.miraheze.org/climatetestwiki/7/70/CCAI_logo_icon_green.svg
It is not square (150 x 174 pixels). Even using the same version here doesn't fix the stretching issue.

### CODE REVIEW

**Comment by marcus-voss** [comment]
Remember I needed several trials with the wiki (as there it was not supposed be square, which it should be on other pages). So I squared the svg and pushed it. However, currently don't have the environment to build Jekyll, so can't try if it works.

**Comment by marcus-voss** [comment]
Btw, Inkscape is a free small tool to work with SVG to change format and export to different sizes of PNG. That's what I used to get the wiki logos to work.

**Comment by priyald17** [comment]
Thanks Marcus! For some reason my machine is not recognizing the new favicon when I build locally (it's defaulting to the CCAI Earth). Do you mind taking a screenshot of what it looks like in your e.g. Chrome tab?

**Comment by priyald17** [comment]
Ah okay, got it, it needs to be a png I believe (svg doesn't work at least for local build). So I've gone ahead and pushed that, will merge.

image

**Pull request merged**
