### PR TITLE
Added David R and Lynn to neurips2020.md

### PR DESCRIPTION
**Pull request by esherwin**
As organizers

### CODE REVIEW

**Comment by priyald17** [comment]
Would suggest adding Lynn after Yumna? So Lynn and David R are in similar places in the list, also

**Comment by esherwin** [comment]
The ordering scheme David D and I agreed on is as follows:
Co-leads in alphabetical order
Other junior authors in alphabetical order
Senior organizers (with faculty jobs) in reverse seniority order

I would prefer we keep this ordering scheme as-is. If we start ordering
junior authors in order of contributions, that would imply that David D is
contributing more than I am. I recognize that most people reading the list
probably won't pick up on this ordering scheme and will likely assume that
David D is contributing more than I am regardless, but this was the deal we
worked out because David D didn't want my name to be first.

Does that make sense?

-Evan

**Comment by priyald17** [comment]
Got it! I guess the question is whether David R is a senior organizer or not, in that case. Junior faculty members can go either way, and he is certainly more in the day-to-day than the current senior organizers. Maybe worth asking him what would be best from his perspective in terms of senior vs junior?

**Review by daviddao — APPROVED** [review]

**Comment by daviddao** [comment]
@priyald17 sure let's ask him! :)

**Pull request merged**
