### PR TITLE
Updating og image url

### PR DESCRIPTION
**Pull request by daviddao**
Using image/NeurIPS2020_preview_copy2.png

### CODE REVIEW

**Comment by asross** [comment]
@daviddao is the image still 960 by 327 (as given by the `og_image_width` and `og_image_height` tags)? If not, you could change those other parameters, but it would actually be best if you could resize it -- that aspect ratio is chosen based on best practices for social media preview images, which can show up with unexpected cutoffs if you go too far off.

**Comment by daviddao** [comment]
Good catch! The current image `NeurIPS2020_preview_copy.png` is just 850x443 and I was wondering which to take. Will replace the file.

**Comment by daviddao** [comment]
Uploaded correctly resized image

**Comment by daviddao** [comment]
@asross actually after having resized it to 960x327 (image/NeurIPS2020_preview_copy2.png), we have some cutoff issues. I think it's wise to maybe revert back to 850x443? 
Screenshot 2020-12-09 at 00 28 08

**Pull request merged**
