### PR TITLE
move tutorials into table

### PR DESCRIPTION
**Pull request by priyald17**
Mirroring the aesthetic on other parts of the site, putting the tutorials into table cells and adding "direct links" to the videos like we do in the workshop pages.

image

### CODE REVIEW

**Comment by asross** [comment]
This looks good to me, though I might try to take a pass at a few alternate designs later today. Feel free to merge if you want to get this in now though!

**Comment by priyald17** [comment]
You're much better at this than I am, so happy to wait for your alt designs for sure :)

**Comment by asross** [comment]
Just pushed up the following tweaks -- let me know what you think!

image

**Comment by priyald17** [comment]
looks good to me!

**Pull request merged**
