### PR TITLE
proposed change to top of homepage, to make CCAI purpose stand out better

### PR DESCRIPTION
**Pull request by priyald17**
In context of the full page:
image

EDITED: Current version
image

### CODE REVIEW

**Comment by marcus-voss** [comment]
Content-wise it looks good to me. Would generally not want "CCAI Resource Wiki", but I think for the link as done it fits. Generally, I would still prefer the Wiki or CCAI Wiki as it sounds a bit nicer. 
Haven't build it, but I guess there is no breaking changes that I could see. Maybe the forwarding needs to be tested once live. But fine to merge, for me.

**Comment by duncanka** [comment]
I don't love this from a design standpoint. I think it's worth visually distinguishing the organization name and the mission.

Better, I think, would be something like this (using H3):
image

**Comment by priyald17** [comment]
> I don't love this from a design standpoint. I think it's worth visually distinguishing the organization name and the mission.
> 
> Better, I think, would be something like this (using H3 and some custom spacing):
> image

I'm fine with that too! I think different organizational websites certainly make different choices about whether they stand out their title or not, e.g., the following don't:
* Future Earth: https://futureearth.org/
* Future of Life Institute: https://futureoflife.org/

But at the same time our logo is rather small on our website. @duncanka Do you want to push your change as the new proposal?

**Comment by priyald17** [comment]
I'm fine with that too! I think different organizational websites certainly make different choices about whether they stand out their name as a title or not, e.g., the following don't:
* Future Earth: https://futureearth.org/
* Future of Life Institute: https://futureoflife.org/

I guess I was feeling that the title name was a bit redundant with having the logo. But at the same time our logo is rather small on our website. @duncanka Do you want to push your change as the new proposal, and include a screenshot of the whole page so we can see it in context?

**Comment by priyald17** [comment]
I guess one thing is that I do sort of like introducing the language "a global initiative" because people often ask what we are. So if there's space for that in the new proposal as well, I'm game.

**Comment by duncanka** [comment]
Ahh, I see what you were going for. Yes, the other pages have more prominent logos, but I think the bigger issue is that when they put that long block of text, it's functioning as a sentence, not a title. I think my concerns would be mostly resolved if we just replaced the colon with "is an" ("Climate Change AI is a global...").

If we go that route, it might also be good to increase the spacing below the title and/or left-align.

**Comment by priyald17** [comment]
That's a good call yeah, I think a sentence is much better. A few versions below, eager to hear thoughts on which is better!

This is what it looks like left-aligned (this is what I've now pushed):
image

This is centered with the current spacing:
image

This is centered with slightly more space:
image

**Comment by duncanka** [comment]
I think I prefer a) centered, b) more space, and c) bigger font (not shown). 😄

**Comment by priyald17** [comment]
This is h1 size, which I think is probably too aggressive: 
image

I don't actually know how to properly do font sizes in between, so I'm just pushing the centered + more space one for now, in the hopes that somebody else might be able to deal with making it bigger? :)

**Comment by duncanka** [comment]
I actually think the big text is probably fine. But if you want to change the size, you could just add something like `style="font-size: 1.75em"`.

Careful with that line break...that won't necessarily work well on mobile.

**Comment by priyald17** [comment]
Good call with the br! This is with 1.75em (in between h1 and h2): 
image

I dunno, somehow I think it looks a bit aggressive and messy to me once it's three lines. I've pushed it with h2 and no br for now, but ofc the font size is still up for debate!

**Comment by priyald17** [comment]
This is the most recent version pushed, for reference
image

**Comment by asross** [comment]
We've resisted this for a while, but I wonder if this might be a good use-case for a hero layout pattern (e.g. https://bulma.io/documentation/layout/hero/, or like https://www.climatechange.ai/events/tedx)

We could have it be relatively small (i.e. not full-page height), perhaps black with the globe image, and this text in white.

(Having a visual designer would really help with this type of change as well 😅)

**Comment by priyald17** [comment]
I would be down, haha. Do you think that is feasible to implement over the next few days, or that we should merge the current version as a stop gap?

**Comment by asross** [comment]
Here's a really rough attempt, let me know if you think something along these lines would be worthwhile, or whether we should just stick with the most recent version:

image

**Comment by asross** [comment]
Might actually be interesting if there were an "AI globe" on the other side of the screen, to echo our logo :)

**Comment by duncanka** [comment]
I am a very big fan of this change. Just needs a period on the end of that sentence. 😄

**Comment by duncanka** [comment]
(Also a fan of the AI globe idea.)

**Comment by priyald17** [comment]
I love this! Agreed with David about removing "is a" in this context. 

Would it work to actually split out the Earth globe and the AI globe from our logo, and actually use those in our banner? If that's too complicated though, I think the look of this is good/nice.

**Comment by priyald17** [comment]
If we use the split out logo parts, I might suggest green as being a nicer profile. It makes the website look brighter, as opposed to black.

**Comment by asross** [comment]
Awesome, I made this change as a separate PR: https://github.com/climatechange-ai/climatechange_ai/pull/162

To @priyald17's point about using separate logo parts / green, I'd be down to implement this and see what it looks like! Just need @konstantinklemmer to send me the split-apart files :)

**Pull request merged**
